//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SiteMapLocalizations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SiteMapLocalizations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SiteMapLocalizations", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增管理员.
        /// </summary>
        internal static string AdminAddtitle {
            get {
                return ResourceManager.GetString("AdminAddtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管理员列表.
        /// </summary>
        internal static string AdminListtitle {
            get {
                return ResourceManager.GetString("AdminListtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增套餐.
        /// </summary>
        internal static string ApkAddSettitle {
            get {
                return ResourceManager.GetString("ApkAddSettitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增安装包.
        /// </summary>
        internal static string ApkAddtitle {
            get {
                return ResourceManager.GetString("ApkAddtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安装包下载历史.
        /// </summary>
        internal static string ApkDownloadhistitle {
            get {
                return ResourceManager.GetString("ApkDownloadhistitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APK安装历史.
        /// </summary>
        internal static string ApkInstallhistitle {
            get {
                return ResourceManager.GetString("ApkInstallhistitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安装包管理.
        /// </summary>
        internal static string ApkInstallTitle {
            get {
                return ResourceManager.GetString("ApkInstallTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安装包列表.
        /// </summary>
        internal static string ApkListtitle {
            get {
                return ResourceManager.GetString("ApkListtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 套餐列表.
        /// </summary>
        internal static string ApkSetListtitle {
            get {
                return ResourceManager.GetString("ApkSetListtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增Patch包.
        /// </summary>
        internal static string AppPatchAddTitle {
            get {
                return ResourceManager.GetString("AppPatchAddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patch列表.
        /// </summary>
        internal static string AppPatchListTitle {
            get {
                return ResourceManager.GetString("AppPatchListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 客户端管理.
        /// </summary>
        internal static string ClientTitle {
            get {
                return ResourceManager.GetString("ClientTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增驱动.
        /// </summary>
        internal static string DriverAddTitle {
            get {
                return ResourceManager.GetString("DriverAddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 驱动下载历史.
        /// </summary>
        internal static string DriverDownLogTitle {
            get {
                return ResourceManager.GetString("DriverDownLogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 驱动列表.
        /// </summary>
        internal static string DriverListTitle {
            get {
                return ResourceManager.GetString("DriverListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 驱动管理.
        /// </summary>
        internal static string DriverTitle {
            get {
                return ResourceManager.GetString("DriverTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 首页.
        /// </summary>
        internal static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增手机.
        /// </summary>
        internal static string PhoneAddTitle {
            get {
                return ResourceManager.GetString("PhoneAddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 手机应用信息.
        /// </summary>
        internal static string PhoneApptitle {
            get {
                return ResourceManager.GetString("PhoneApptitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 手机列表.
        /// </summary>
        internal static string PhoneListTitle {
            get {
                return ResourceManager.GetString("PhoneListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 手机管理.
        /// </summary>
        internal static string PhoneTitle {
            get {
                return ResourceManager.GetString("PhoneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统管理.
        /// </summary>
        internal static string SystemTitle {
            get {
                return ResourceManager.GetString("SystemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增用户.
        /// </summary>
        internal static string UserAddtitle {
            get {
                return ResourceManager.GetString("UserAddtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户列表.
        /// </summary>
        internal static string UserListtitle {
            get {
                return ResourceManager.GetString("UserListtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户管理.
        /// </summary>
        internal static string UserTitle {
            get {
                return ResourceManager.GetString("UserTitle", resourceCulture);
            }
        }
    }
}
