#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageSite.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="apkinstaller")]
	public partial class SqlDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_admin(tbl_admin instance);
    partial void Updatetbl_admin(tbl_admin instance);
    partial void Deletetbl_admin(tbl_admin instance);
    partial void Inserttbl_user(tbl_user instance);
    partial void Updatetbl_user(tbl_user instance);
    partial void Deletetbl_user(tbl_user instance);
    partial void Inserttbl_apkdownlog(tbl_apkdownlog instance);
    partial void Updatetbl_apkdownlog(tbl_apkdownlog instance);
    partial void Deletetbl_apkdownlog(tbl_apkdownlog instance);
    partial void Inserttbl_apkgroup(tbl_apkgroup instance);
    partial void Updatetbl_apkgroup(tbl_apkgroup instance);
    partial void Deletetbl_apkgroup(tbl_apkgroup instance);
    partial void Inserttbl_apkinfo(tbl_apkinfo instance);
    partial void Updatetbl_apkinfo(tbl_apkinfo instance);
    partial void Deletetbl_apkinfo(tbl_apkinfo instance);
    partial void Inserttbl_apkinstalllog(tbl_apkinstalllog instance);
    partial void Updatetbl_apkinstalllog(tbl_apkinstalllog instance);
    partial void Deletetbl_apkinstalllog(tbl_apkinstalllog instance);
    partial void Inserttbl_apppatch(tbl_apppatch instance);
    partial void Updatetbl_apppatch(tbl_apppatch instance);
    partial void Deletetbl_apppatch(tbl_apppatch instance);
    partial void Inserttbl_authlog(tbl_authlog instance);
    partial void Updatetbl_authlog(tbl_authlog instance);
    partial void Deletetbl_authlog(tbl_authlog instance);
    partial void Inserttbl_driverdownlog(tbl_driverdownlog instance);
    partial void Updatetbl_driverdownlog(tbl_driverdownlog instance);
    partial void Deletetbl_driverdownlog(tbl_driverdownlog instance);
    partial void Inserttbl_driverinfo(tbl_driverinfo instance);
    partial void Updatetbl_driverinfo(tbl_driverinfo instance);
    partial void Deletetbl_driverinfo(tbl_driverinfo instance);
    partial void Inserttbl_telapp(tbl_telapp instance);
    partial void Updatetbl_telapp(tbl_telapp instance);
    partial void Deletetbl_telapp(tbl_telapp instance);
    partial void Inserttbl_telinfo(tbl_telinfo instance);
    partial void Updatetbl_telinfo(tbl_telinfo instance);
    partial void Deletetbl_telinfo(tbl_telinfo instance);
    #endregion
		
		public SqlDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["apkinstallerConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SqlDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SqlDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SqlDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SqlDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_admin> tbl_admins
		{
			get
			{
				return this.GetTable<tbl_admin>();
			}
		}
		
		public System.Data.Linq.Table<tbl_user> tbl_users
		{
			get
			{
				return this.GetTable<tbl_user>();
			}
		}
		
		public System.Data.Linq.Table<tbl_apkdownlog> tbl_apkdownlogs
		{
			get
			{
				return this.GetTable<tbl_apkdownlog>();
			}
		}
		
		public System.Data.Linq.Table<tbl_apkgroup> tbl_apkgroups
		{
			get
			{
				return this.GetTable<tbl_apkgroup>();
			}
		}
		
		public System.Data.Linq.Table<tbl_apkinfo> tbl_apkinfos
		{
			get
			{
				return this.GetTable<tbl_apkinfo>();
			}
		}
		
		public System.Data.Linq.Table<tbl_apkinstalllog> tbl_apkinstalllogs
		{
			get
			{
				return this.GetTable<tbl_apkinstalllog>();
			}
		}
		
		public System.Data.Linq.Table<tbl_apppatch> tbl_apppatches
		{
			get
			{
				return this.GetTable<tbl_apppatch>();
			}
		}
		
		public System.Data.Linq.Table<tbl_authlog> tbl_authlogs
		{
			get
			{
				return this.GetTable<tbl_authlog>();
			}
		}
		
		public System.Data.Linq.Table<tbl_driverdownlog> tbl_driverdownlogs
		{
			get
			{
				return this.GetTable<tbl_driverdownlog>();
			}
		}
		
		public System.Data.Linq.Table<tbl_driverinfo> tbl_driverinfos
		{
			get
			{
				return this.GetTable<tbl_driverinfo>();
			}
		}
		
		public System.Data.Linq.Table<tbl_telapp> tbl_telapps
		{
			get
			{
				return this.GetTable<tbl_telapp>();
			}
		}
		
		public System.Data.Linq.Table<tbl_telinfo> tbl_telinfos
		{
			get
			{
				return this.GetTable<tbl_telinfo>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_admin")]
	public partial class tbl_admin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _uid;
		
		private string _name;
		
		private string _realname;
		
		private string _password;
		
		private string _mailaddress;
		
		private string _imgpath;
		
		private string _role;
		
		private byte _status;
		
		private System.DateTime _regtime;
		
		private byte _deleted;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuidChanging(long value);
    partial void OnuidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnrealnameChanging(string value);
    partial void OnrealnameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnmailaddressChanging(string value);
    partial void OnmailaddressChanged();
    partial void OnimgpathChanging(string value);
    partial void OnimgpathChanged();
    partial void OnroleChanging(string value);
    partial void OnroleChanged();
    partial void OnstatusChanging(byte value);
    partial void OnstatusChanged();
    partial void OnregtimeChanging(System.DateTime value);
    partial void OnregtimeChanged();
    partial void OndeletedChanging(byte value);
    partial void OndeletedChanged();
    #endregion
		
		public tbl_admin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uid", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long uid
		{
			get
			{
				return this._uid;
			}
			set
			{
				if ((this._uid != value))
				{
					this.OnuidChanging(value);
					this.SendPropertyChanging();
					this._uid = value;
					this.SendPropertyChanged("uid");
					this.OnuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_realname", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string realname
		{
			get
			{
				return this._realname;
			}
			set
			{
				if ((this._realname != value))
				{
					this.OnrealnameChanging(value);
					this.SendPropertyChanging();
					this._realname = value;
					this.SendPropertyChanged("realname");
					this.OnrealnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mailaddress", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string mailaddress
		{
			get
			{
				return this._mailaddress;
			}
			set
			{
				if ((this._mailaddress != value))
				{
					this.OnmailaddressChanging(value);
					this.SendPropertyChanging();
					this._mailaddress = value;
					this.SendPropertyChanged("mailaddress");
					this.OnmailaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imgpath", DbType="NVarChar(300)")]
		public string imgpath
		{
			get
			{
				return this._imgpath;
			}
			set
			{
				if ((this._imgpath != value))
				{
					this.OnimgpathChanging(value);
					this.SendPropertyChanging();
					this._imgpath = value;
					this.SendPropertyChanged("imgpath");
					this.OnimgpathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_role", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string role
		{
			get
			{
				return this._role;
			}
			set
			{
				if ((this._role != value))
				{
					this.OnroleChanging(value);
					this.SendPropertyChanging();
					this._role = value;
					this.SendPropertyChanged("role");
					this.OnroleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="TinyInt NOT NULL")]
		public byte status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_regtime", DbType="DateTime NOT NULL")]
		public System.DateTime regtime
		{
			get
			{
				return this._regtime;
			}
			set
			{
				if ((this._regtime != value))
				{
					this.OnregtimeChanging(value);
					this.SendPropertyChanging();
					this._regtime = value;
					this.SendPropertyChanged("regtime");
					this.OnregtimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleted", DbType="TinyInt NOT NULL")]
		public byte deleted
		{
			get
			{
				return this._deleted;
			}
			set
			{
				if ((this._deleted != value))
				{
					this.OndeletedChanging(value);
					this.SendPropertyChanging();
					this._deleted = value;
					this.SendPropertyChanged("deleted");
					this.OndeletedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_user")]
	public partial class tbl_user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _uid;
		
		private System.Nullable<long> _parentid;
		
		private byte _userlevel;
		
		private string _username;
		
		private string _password;
		
		private byte _deleted;
		
		private EntitySet<tbl_apkdownlog> _tbl_apkdownlogs;
		
		private EntitySet<tbl_driverdownlog> _tbl_driverdownlogs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuidChanging(long value);
    partial void OnuidChanged();
    partial void OnparentidChanging(System.Nullable<long> value);
    partial void OnparentidChanged();
    partial void OnuserlevelChanging(byte value);
    partial void OnuserlevelChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OndeletedChanging(byte value);
    partial void OndeletedChanged();
    #endregion
		
		public tbl_user()
		{
			this._tbl_apkdownlogs = new EntitySet<tbl_apkdownlog>(new Action<tbl_apkdownlog>(this.attach_tbl_apkdownlogs), new Action<tbl_apkdownlog>(this.detach_tbl_apkdownlogs));
			this._tbl_driverdownlogs = new EntitySet<tbl_driverdownlog>(new Action<tbl_driverdownlog>(this.attach_tbl_driverdownlogs), new Action<tbl_driverdownlog>(this.detach_tbl_driverdownlogs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uid", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long uid
		{
			get
			{
				return this._uid;
			}
			set
			{
				if ((this._uid != value))
				{
					this.OnuidChanging(value);
					this.SendPropertyChanging();
					this._uid = value;
					this.SendPropertyChanged("uid");
					this.OnuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parentid", DbType="BigInt")]
		public System.Nullable<long> parentid
		{
			get
			{
				return this._parentid;
			}
			set
			{
				if ((this._parentid != value))
				{
					this.OnparentidChanging(value);
					this.SendPropertyChanging();
					this._parentid = value;
					this.SendPropertyChanged("parentid");
					this.OnparentidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userlevel", DbType="TinyInt NOT NULL")]
		public byte userlevel
		{
			get
			{
				return this._userlevel;
			}
			set
			{
				if ((this._userlevel != value))
				{
					this.OnuserlevelChanging(value);
					this.SendPropertyChanging();
					this._userlevel = value;
					this.SendPropertyChanged("userlevel");
					this.OnuserlevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleted", DbType="TinyInt NOT NULL")]
		public byte deleted
		{
			get
			{
				return this._deleted;
			}
			set
			{
				if ((this._deleted != value))
				{
					this.OndeletedChanging(value);
					this.SendPropertyChanging();
					this._deleted = value;
					this.SendPropertyChanged("deleted");
					this.OndeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_user_tbl_apkdownlog", Storage="_tbl_apkdownlogs", ThisKey="uid", OtherKey="userid")]
		public EntitySet<tbl_apkdownlog> tbl_apkdownlogs
		{
			get
			{
				return this._tbl_apkdownlogs;
			}
			set
			{
				this._tbl_apkdownlogs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_user_tbl_driverdownlog", Storage="_tbl_driverdownlogs", ThisKey="uid", OtherKey="userid")]
		public EntitySet<tbl_driverdownlog> tbl_driverdownlogs
		{
			get
			{
				return this._tbl_driverdownlogs;
			}
			set
			{
				this._tbl_driverdownlogs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_apkdownlogs(tbl_apkdownlog entity)
		{
			this.SendPropertyChanging();
			entity.tbl_user = this;
		}
		
		private void detach_tbl_apkdownlogs(tbl_apkdownlog entity)
		{
			this.SendPropertyChanging();
			entity.tbl_user = null;
		}
		
		private void attach_tbl_driverdownlogs(tbl_driverdownlog entity)
		{
			this.SendPropertyChanging();
			entity.tbl_user = this;
		}
		
		private void detach_tbl_driverdownlogs(tbl_driverdownlog entity)
		{
			this.SendPropertyChanging();
			entity.tbl_user = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_apkdownlog")]
	public partial class tbl_apkdownlog : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _uid;
		
		private long _userid;
		
		private long _apkid;
		
		private System.Nullable<System.DateTime> _downstartdate;
		
		private System.Nullable<System.DateTime> _downenddate;
		
		private byte _result;
		
		private byte _deleted;
		
		private EntityRef<tbl_apkdownlog> _tbl_apkdownlog2;
		
		private EntityRef<tbl_apkdownlog> _tbl_apkdownlog4;
		
		private EntityRef<tbl_apkdownlog> _tbl_apkdownlog1;
		
		private EntityRef<tbl_apkdownlog> _tbl_apkdownlog3;
		
		private EntityRef<tbl_user> _tbl_user;
		
		private EntityRef<tbl_apkinfo> _tbl_apkinfo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuidChanging(long value);
    partial void OnuidChanged();
    partial void OnuseridChanging(long value);
    partial void OnuseridChanged();
    partial void OnapkidChanging(long value);
    partial void OnapkidChanged();
    partial void OndownstartdateChanging(System.Nullable<System.DateTime> value);
    partial void OndownstartdateChanged();
    partial void OndownenddateChanging(System.Nullable<System.DateTime> value);
    partial void OndownenddateChanged();
    partial void OnresultChanging(byte value);
    partial void OnresultChanged();
    partial void OndeletedChanging(byte value);
    partial void OndeletedChanged();
    #endregion
		
		public tbl_apkdownlog()
		{
			this._tbl_apkdownlog2 = default(EntityRef<tbl_apkdownlog>);
			this._tbl_apkdownlog4 = default(EntityRef<tbl_apkdownlog>);
			this._tbl_apkdownlog1 = default(EntityRef<tbl_apkdownlog>);
			this._tbl_apkdownlog3 = default(EntityRef<tbl_apkdownlog>);
			this._tbl_user = default(EntityRef<tbl_user>);
			this._tbl_apkinfo = default(EntityRef<tbl_apkinfo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uid", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long uid
		{
			get
			{
				return this._uid;
			}
			set
			{
				if ((this._uid != value))
				{
					if ((this._tbl_apkdownlog1.HasLoadedOrAssignedValue || this._tbl_apkdownlog3.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnuidChanging(value);
					this.SendPropertyChanging();
					this._uid = value;
					this.SendPropertyChanged("uid");
					this.OnuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="BigInt NOT NULL")]
		public long userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					if (this._tbl_user.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnuseridChanging(value);
					this.SendPropertyChanging();
					this._userid = value;
					this.SendPropertyChanged("userid");
					this.OnuseridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apkid", DbType="BigInt NOT NULL")]
		public long apkid
		{
			get
			{
				return this._apkid;
			}
			set
			{
				if ((this._apkid != value))
				{
					if (this._tbl_apkinfo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnapkidChanging(value);
					this.SendPropertyChanging();
					this._apkid = value;
					this.SendPropertyChanged("apkid");
					this.OnapkidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_downstartdate", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> downstartdate
		{
			get
			{
				return this._downstartdate;
			}
			set
			{
				if ((this._downstartdate != value))
				{
					this.OndownstartdateChanging(value);
					this.SendPropertyChanging();
					this._downstartdate = value;
					this.SendPropertyChanged("downstartdate");
					this.OndownstartdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_downenddate", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> downenddate
		{
			get
			{
				return this._downenddate;
			}
			set
			{
				if ((this._downenddate != value))
				{
					this.OndownenddateChanging(value);
					this.SendPropertyChanging();
					this._downenddate = value;
					this.SendPropertyChanged("downenddate");
					this.OndownenddateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_result", DbType="TinyInt NOT NULL")]
		public byte result
		{
			get
			{
				return this._result;
			}
			set
			{
				if ((this._result != value))
				{
					this.OnresultChanging(value);
					this.SendPropertyChanging();
					this._result = value;
					this.SendPropertyChanged("result");
					this.OnresultChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleted", DbType="TinyInt NOT NULL")]
		public byte deleted
		{
			get
			{
				return this._deleted;
			}
			set
			{
				if ((this._deleted != value))
				{
					this.OndeletedChanging(value);
					this.SendPropertyChanging();
					this._deleted = value;
					this.SendPropertyChanged("deleted");
					this.OndeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_apkdownlog_tbl_apkdownlog", Storage="_tbl_apkdownlog2", ThisKey="uid", OtherKey="uid", IsUnique=true, IsForeignKey=false)]
		public tbl_apkdownlog tbl_apkdownlog2
		{
			get
			{
				return this._tbl_apkdownlog2.Entity;
			}
			set
			{
				tbl_apkdownlog previousValue = this._tbl_apkdownlog2.Entity;
				if (((previousValue != value) 
							|| (this._tbl_apkdownlog2.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_apkdownlog2.Entity = null;
						previousValue.tbl_apkdownlog1 = null;
					}
					this._tbl_apkdownlog2.Entity = value;
					if ((value != null))
					{
						value.tbl_apkdownlog1 = this;
					}
					this.SendPropertyChanged("tbl_apkdownlog2");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_apkdownlog_tbl_apkdownlog1", Storage="_tbl_apkdownlog4", ThisKey="uid", OtherKey="uid", IsUnique=true, IsForeignKey=false)]
		public tbl_apkdownlog tbl_apkdownlog4
		{
			get
			{
				return this._tbl_apkdownlog4.Entity;
			}
			set
			{
				tbl_apkdownlog previousValue = this._tbl_apkdownlog4.Entity;
				if (((previousValue != value) 
							|| (this._tbl_apkdownlog4.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_apkdownlog4.Entity = null;
						previousValue.tbl_apkdownlog3 = null;
					}
					this._tbl_apkdownlog4.Entity = value;
					if ((value != null))
					{
						value.tbl_apkdownlog3 = this;
					}
					this.SendPropertyChanged("tbl_apkdownlog4");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_apkdownlog_tbl_apkdownlog", Storage="_tbl_apkdownlog1", ThisKey="uid", OtherKey="uid", IsForeignKey=true)]
		public tbl_apkdownlog tbl_apkdownlog1
		{
			get
			{
				return this._tbl_apkdownlog1.Entity;
			}
			set
			{
				tbl_apkdownlog previousValue = this._tbl_apkdownlog1.Entity;
				if (((previousValue != value) 
							|| (this._tbl_apkdownlog1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_apkdownlog1.Entity = null;
						previousValue.tbl_apkdownlog2 = null;
					}
					this._tbl_apkdownlog1.Entity = value;
					if ((value != null))
					{
						value.tbl_apkdownlog2 = this;
						this._uid = value.uid;
					}
					else
					{
						this._uid = default(long);
					}
					this.SendPropertyChanged("tbl_apkdownlog1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_apkdownlog_tbl_apkdownlog1", Storage="_tbl_apkdownlog3", ThisKey="uid", OtherKey="uid", IsForeignKey=true)]
		public tbl_apkdownlog tbl_apkdownlog3
		{
			get
			{
				return this._tbl_apkdownlog3.Entity;
			}
			set
			{
				tbl_apkdownlog previousValue = this._tbl_apkdownlog3.Entity;
				if (((previousValue != value) 
							|| (this._tbl_apkdownlog3.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_apkdownlog3.Entity = null;
						previousValue.tbl_apkdownlog4 = null;
					}
					this._tbl_apkdownlog3.Entity = value;
					if ((value != null))
					{
						value.tbl_apkdownlog4 = this;
						this._uid = value.uid;
					}
					else
					{
						this._uid = default(long);
					}
					this.SendPropertyChanged("tbl_apkdownlog3");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_user_tbl_apkdownlog", Storage="_tbl_user", ThisKey="userid", OtherKey="uid", IsForeignKey=true)]
		public tbl_user tbl_user
		{
			get
			{
				return this._tbl_user.Entity;
			}
			set
			{
				tbl_user previousValue = this._tbl_user.Entity;
				if (((previousValue != value) 
							|| (this._tbl_user.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_user.Entity = null;
						previousValue.tbl_apkdownlogs.Remove(this);
					}
					this._tbl_user.Entity = value;
					if ((value != null))
					{
						value.tbl_apkdownlogs.Add(this);
						this._userid = value.uid;
					}
					else
					{
						this._userid = default(long);
					}
					this.SendPropertyChanged("tbl_user");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_apkinfo_tbl_apkdownlog", Storage="_tbl_apkinfo", ThisKey="apkid", OtherKey="uid", IsForeignKey=true)]
		public tbl_apkinfo tbl_apkinfo
		{
			get
			{
				return this._tbl_apkinfo.Entity;
			}
			set
			{
				tbl_apkinfo previousValue = this._tbl_apkinfo.Entity;
				if (((previousValue != value) 
							|| (this._tbl_apkinfo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_apkinfo.Entity = null;
						previousValue.tbl_apkdownlogs.Remove(this);
					}
					this._tbl_apkinfo.Entity = value;
					if ((value != null))
					{
						value.tbl_apkdownlogs.Add(this);
						this._apkid = value.uid;
					}
					else
					{
						this._apkid = default(long);
					}
					this.SendPropertyChanged("tbl_apkinfo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_apkgroup")]
	public partial class tbl_apkgroup : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _uid;
		
		private string _name;
		
		private byte _gtype;
		
		private string _userids;
		
		private string _imgpath;
		
		private System.DateTime _createtime;
		
		private byte _deleted;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuidChanging(long value);
    partial void OnuidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OngtypeChanging(byte value);
    partial void OngtypeChanged();
    partial void OnuseridsChanging(string value);
    partial void OnuseridsChanged();
    partial void OnimgpathChanging(string value);
    partial void OnimgpathChanged();
    partial void OncreatetimeChanging(System.DateTime value);
    partial void OncreatetimeChanged();
    partial void OndeletedChanging(byte value);
    partial void OndeletedChanged();
    #endregion
		
		public tbl_apkgroup()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uid", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long uid
		{
			get
			{
				return this._uid;
			}
			set
			{
				if ((this._uid != value))
				{
					this.OnuidChanging(value);
					this.SendPropertyChanging();
					this._uid = value;
					this.SendPropertyChanged("uid");
					this.OnuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gtype", DbType="TinyInt NOT NULL")]
		public byte gtype
		{
			get
			{
				return this._gtype;
			}
			set
			{
				if ((this._gtype != value))
				{
					this.OngtypeChanging(value);
					this.SendPropertyChanging();
					this._gtype = value;
					this.SendPropertyChanged("gtype");
					this.OngtypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userids", DbType="NVarChar(300)")]
		public string userids
		{
			get
			{
				return this._userids;
			}
			set
			{
				if ((this._userids != value))
				{
					this.OnuseridsChanging(value);
					this.SendPropertyChanging();
					this._userids = value;
					this.SendPropertyChanged("userids");
					this.OnuseridsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imgpath", DbType="NVarChar(300)")]
		public string imgpath
		{
			get
			{
				return this._imgpath;
			}
			set
			{
				if ((this._imgpath != value))
				{
					this.OnimgpathChanging(value);
					this.SendPropertyChanging();
					this._imgpath = value;
					this.SendPropertyChanged("imgpath");
					this.OnimgpathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createtime", DbType="SmallDateTime NOT NULL")]
		public System.DateTime createtime
		{
			get
			{
				return this._createtime;
			}
			set
			{
				if ((this._createtime != value))
				{
					this.OncreatetimeChanging(value);
					this.SendPropertyChanging();
					this._createtime = value;
					this.SendPropertyChanged("createtime");
					this.OncreatetimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleted", DbType="TinyInt NOT NULL")]
		public byte deleted
		{
			get
			{
				return this._deleted;
			}
			set
			{
				if ((this._deleted != value))
				{
					this.OndeletedChanging(value);
					this.SendPropertyChanging();
					this._deleted = value;
					this.SendPropertyChanged("deleted");
					this.OndeletedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_apkinfo")]
	public partial class tbl_apkinfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _uid;
		
		private string _groupids;
		
		private string _name;
		
		private string _filepath;
		
		private string _imgpath;
		
		private System.Nullable<long> _filesize;
		
		private string _version;
		
		private System.Nullable<long> _property;
		
		private System.DateTime _createtime;
		
		private int _showorder;
		
		private byte _deleted;
		
		private EntitySet<tbl_apkdownlog> _tbl_apkdownlogs;
		
		private EntitySet<tbl_apkinstalllog> _tbl_apkinstalllogs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuidChanging(long value);
    partial void OnuidChanged();
    partial void OngroupidsChanging(string value);
    partial void OngroupidsChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnfilepathChanging(string value);
    partial void OnfilepathChanged();
    partial void OnimgpathChanging(string value);
    partial void OnimgpathChanged();
    partial void OnfilesizeChanging(System.Nullable<long> value);
    partial void OnfilesizeChanged();
    partial void OnversionChanging(string value);
    partial void OnversionChanged();
    partial void OnpropertyChanging(System.Nullable<long> value);
    partial void OnpropertyChanged();
    partial void OncreatetimeChanging(System.DateTime value);
    partial void OncreatetimeChanged();
    partial void OnshoworderChanging(int value);
    partial void OnshoworderChanged();
    partial void OndeletedChanging(byte value);
    partial void OndeletedChanged();
    #endregion
		
		public tbl_apkinfo()
		{
			this._tbl_apkdownlogs = new EntitySet<tbl_apkdownlog>(new Action<tbl_apkdownlog>(this.attach_tbl_apkdownlogs), new Action<tbl_apkdownlog>(this.detach_tbl_apkdownlogs));
			this._tbl_apkinstalllogs = new EntitySet<tbl_apkinstalllog>(new Action<tbl_apkinstalllog>(this.attach_tbl_apkinstalllogs), new Action<tbl_apkinstalllog>(this.detach_tbl_apkinstalllogs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uid", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long uid
		{
			get
			{
				return this._uid;
			}
			set
			{
				if ((this._uid != value))
				{
					this.OnuidChanging(value);
					this.SendPropertyChanging();
					this._uid = value;
					this.SendPropertyChanged("uid");
					this.OnuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_groupids", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string groupids
		{
			get
			{
				return this._groupids;
			}
			set
			{
				if ((this._groupids != value))
				{
					this.OngroupidsChanging(value);
					this.SendPropertyChanging();
					this._groupids = value;
					this.SendPropertyChanged("groupids");
					this.OngroupidsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_filepath", DbType="NVarChar(300)")]
		public string filepath
		{
			get
			{
				return this._filepath;
			}
			set
			{
				if ((this._filepath != value))
				{
					this.OnfilepathChanging(value);
					this.SendPropertyChanging();
					this._filepath = value;
					this.SendPropertyChanged("filepath");
					this.OnfilepathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imgpath", DbType="NVarChar(300)")]
		public string imgpath
		{
			get
			{
				return this._imgpath;
			}
			set
			{
				if ((this._imgpath != value))
				{
					this.OnimgpathChanging(value);
					this.SendPropertyChanging();
					this._imgpath = value;
					this.SendPropertyChanged("imgpath");
					this.OnimgpathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_filesize", DbType="BigInt")]
		public System.Nullable<long> filesize
		{
			get
			{
				return this._filesize;
			}
			set
			{
				if ((this._filesize != value))
				{
					this.OnfilesizeChanging(value);
					this.SendPropertyChanging();
					this._filesize = value;
					this.SendPropertyChanged("filesize");
					this.OnfilesizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_version", DbType="NVarChar(20)")]
		public string version
		{
			get
			{
				return this._version;
			}
			set
			{
				if ((this._version != value))
				{
					this.OnversionChanging(value);
					this.SendPropertyChanging();
					this._version = value;
					this.SendPropertyChanged("version");
					this.OnversionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_property", DbType="BigInt")]
		public System.Nullable<long> property
		{
			get
			{
				return this._property;
			}
			set
			{
				if ((this._property != value))
				{
					this.OnpropertyChanging(value);
					this.SendPropertyChanging();
					this._property = value;
					this.SendPropertyChanged("property");
					this.OnpropertyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createtime", DbType="SmallDateTime NOT NULL")]
		public System.DateTime createtime
		{
			get
			{
				return this._createtime;
			}
			set
			{
				if ((this._createtime != value))
				{
					this.OncreatetimeChanging(value);
					this.SendPropertyChanging();
					this._createtime = value;
					this.SendPropertyChanged("createtime");
					this.OncreatetimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_showorder", DbType="Int NOT NULL")]
		public int showorder
		{
			get
			{
				return this._showorder;
			}
			set
			{
				if ((this._showorder != value))
				{
					this.OnshoworderChanging(value);
					this.SendPropertyChanging();
					this._showorder = value;
					this.SendPropertyChanged("showorder");
					this.OnshoworderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleted", DbType="TinyInt NOT NULL")]
		public byte deleted
		{
			get
			{
				return this._deleted;
			}
			set
			{
				if ((this._deleted != value))
				{
					this.OndeletedChanging(value);
					this.SendPropertyChanging();
					this._deleted = value;
					this.SendPropertyChanged("deleted");
					this.OndeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_apkinfo_tbl_apkdownlog", Storage="_tbl_apkdownlogs", ThisKey="uid", OtherKey="apkid")]
		public EntitySet<tbl_apkdownlog> tbl_apkdownlogs
		{
			get
			{
				return this._tbl_apkdownlogs;
			}
			set
			{
				this._tbl_apkdownlogs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_apkinfo_tbl_apkinstalllog", Storage="_tbl_apkinstalllogs", ThisKey="uid", OtherKey="apkid")]
		public EntitySet<tbl_apkinstalllog> tbl_apkinstalllogs
		{
			get
			{
				return this._tbl_apkinstalllogs;
			}
			set
			{
				this._tbl_apkinstalllogs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_apkdownlogs(tbl_apkdownlog entity)
		{
			this.SendPropertyChanging();
			entity.tbl_apkinfo = this;
		}
		
		private void detach_tbl_apkdownlogs(tbl_apkdownlog entity)
		{
			this.SendPropertyChanging();
			entity.tbl_apkinfo = null;
		}
		
		private void attach_tbl_apkinstalllogs(tbl_apkinstalllog entity)
		{
			this.SendPropertyChanging();
			entity.tbl_apkinfo = this;
		}
		
		private void detach_tbl_apkinstalllogs(tbl_apkinstalllog entity)
		{
			this.SendPropertyChanging();
			entity.tbl_apkinfo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_apkinstalllog")]
	public partial class tbl_apkinstalllog : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _uid;
		
		private long _userid;
		
		private System.Nullable<long> _apkid;
		
		private string _apkname;
		
		private long _telid;
		
		private byte _logtype;
		
		private System.DateTime _createtime;
		
		private byte _status;
		
		private string _note;
		
		private string _clientver;
		
		private string _remoteip;
		
		private byte _deleted;
		
		private EntityRef<tbl_apkinfo> _tbl_apkinfo;
		
		private EntityRef<tbl_telinfo> _tbl_telinfo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuidChanging(long value);
    partial void OnuidChanged();
    partial void OnuseridChanging(long value);
    partial void OnuseridChanged();
    partial void OnapkidChanging(System.Nullable<long> value);
    partial void OnapkidChanged();
    partial void OnapknameChanging(string value);
    partial void OnapknameChanged();
    partial void OntelidChanging(long value);
    partial void OntelidChanged();
    partial void OnlogtypeChanging(byte value);
    partial void OnlogtypeChanged();
    partial void OncreatetimeChanging(System.DateTime value);
    partial void OncreatetimeChanged();
    partial void OnstatusChanging(byte value);
    partial void OnstatusChanged();
    partial void OnnoteChanging(string value);
    partial void OnnoteChanged();
    partial void OnclientverChanging(string value);
    partial void OnclientverChanged();
    partial void OnremoteipChanging(string value);
    partial void OnremoteipChanged();
    partial void OndeletedChanging(byte value);
    partial void OndeletedChanged();
    #endregion
		
		public tbl_apkinstalllog()
		{
			this._tbl_apkinfo = default(EntityRef<tbl_apkinfo>);
			this._tbl_telinfo = default(EntityRef<tbl_telinfo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uid", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long uid
		{
			get
			{
				return this._uid;
			}
			set
			{
				if ((this._uid != value))
				{
					this.OnuidChanging(value);
					this.SendPropertyChanging();
					this._uid = value;
					this.SendPropertyChanged("uid");
					this.OnuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="BigInt NOT NULL")]
		public long userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					this.OnuseridChanging(value);
					this.SendPropertyChanging();
					this._userid = value;
					this.SendPropertyChanged("userid");
					this.OnuseridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apkid", DbType="BigInt")]
		public System.Nullable<long> apkid
		{
			get
			{
				return this._apkid;
			}
			set
			{
				if ((this._apkid != value))
				{
					if (this._tbl_apkinfo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnapkidChanging(value);
					this.SendPropertyChanging();
					this._apkid = value;
					this.SendPropertyChanged("apkid");
					this.OnapkidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apkname", DbType="NVarChar(50)")]
		public string apkname
		{
			get
			{
				return this._apkname;
			}
			set
			{
				if ((this._apkname != value))
				{
					this.OnapknameChanging(value);
					this.SendPropertyChanging();
					this._apkname = value;
					this.SendPropertyChanged("apkname");
					this.OnapknameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telid", DbType="BigInt NOT NULL")]
		public long telid
		{
			get
			{
				return this._telid;
			}
			set
			{
				if ((this._telid != value))
				{
					if (this._tbl_telinfo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OntelidChanging(value);
					this.SendPropertyChanging();
					this._telid = value;
					this.SendPropertyChanged("telid");
					this.OntelidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logtype", DbType="TinyInt NOT NULL")]
		public byte logtype
		{
			get
			{
				return this._logtype;
			}
			set
			{
				if ((this._logtype != value))
				{
					this.OnlogtypeChanging(value);
					this.SendPropertyChanging();
					this._logtype = value;
					this.SendPropertyChanged("logtype");
					this.OnlogtypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createtime", DbType="DateTime NOT NULL")]
		public System.DateTime createtime
		{
			get
			{
				return this._createtime;
			}
			set
			{
				if ((this._createtime != value))
				{
					this.OncreatetimeChanging(value);
					this.SendPropertyChanging();
					this._createtime = value;
					this.SendPropertyChanged("createtime");
					this.OncreatetimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="TinyInt NOT NULL")]
		public byte status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_note", DbType="NVarChar(300)")]
		public string note
		{
			get
			{
				return this._note;
			}
			set
			{
				if ((this._note != value))
				{
					this.OnnoteChanging(value);
					this.SendPropertyChanging();
					this._note = value;
					this.SendPropertyChanged("note");
					this.OnnoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clientver", DbType="NVarChar(50)")]
		public string clientver
		{
			get
			{
				return this._clientver;
			}
			set
			{
				if ((this._clientver != value))
				{
					this.OnclientverChanging(value);
					this.SendPropertyChanging();
					this._clientver = value;
					this.SendPropertyChanged("clientver");
					this.OnclientverChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remoteip", DbType="NVarChar(20)")]
		public string remoteip
		{
			get
			{
				return this._remoteip;
			}
			set
			{
				if ((this._remoteip != value))
				{
					this.OnremoteipChanging(value);
					this.SendPropertyChanging();
					this._remoteip = value;
					this.SendPropertyChanged("remoteip");
					this.OnremoteipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleted", DbType="TinyInt NOT NULL")]
		public byte deleted
		{
			get
			{
				return this._deleted;
			}
			set
			{
				if ((this._deleted != value))
				{
					this.OndeletedChanging(value);
					this.SendPropertyChanging();
					this._deleted = value;
					this.SendPropertyChanged("deleted");
					this.OndeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_apkinfo_tbl_apkinstalllog", Storage="_tbl_apkinfo", ThisKey="apkid", OtherKey="uid", IsForeignKey=true)]
		public tbl_apkinfo tbl_apkinfo
		{
			get
			{
				return this._tbl_apkinfo.Entity;
			}
			set
			{
				tbl_apkinfo previousValue = this._tbl_apkinfo.Entity;
				if (((previousValue != value) 
							|| (this._tbl_apkinfo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_apkinfo.Entity = null;
						previousValue.tbl_apkinstalllogs.Remove(this);
					}
					this._tbl_apkinfo.Entity = value;
					if ((value != null))
					{
						value.tbl_apkinstalllogs.Add(this);
						this._apkid = value.uid;
					}
					else
					{
						this._apkid = default(Nullable<long>);
					}
					this.SendPropertyChanged("tbl_apkinfo");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_telinfo_tbl_apkinstalllog", Storage="_tbl_telinfo", ThisKey="telid", OtherKey="uid", IsForeignKey=true)]
		public tbl_telinfo tbl_telinfo
		{
			get
			{
				return this._tbl_telinfo.Entity;
			}
			set
			{
				tbl_telinfo previousValue = this._tbl_telinfo.Entity;
				if (((previousValue != value) 
							|| (this._tbl_telinfo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_telinfo.Entity = null;
						previousValue.tbl_apkinstalllogs.Remove(this);
					}
					this._tbl_telinfo.Entity = value;
					if ((value != null))
					{
						value.tbl_apkinstalllogs.Add(this);
						this._telid = value.uid;
					}
					else
					{
						this._telid = default(long);
					}
					this.SendPropertyChanged("tbl_telinfo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_apppatch")]
	public partial class tbl_apppatch : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _uid;
		
		private int _versionCode;
		
		private string _versionName;
		
		private string _patchpath;
		
		private System.DateTime _createtime;
		
		private byte _deleted;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuidChanging(long value);
    partial void OnuidChanged();
    partial void OnversionCodeChanging(int value);
    partial void OnversionCodeChanged();
    partial void OnversionNameChanging(string value);
    partial void OnversionNameChanged();
    partial void OnpatchpathChanging(string value);
    partial void OnpatchpathChanged();
    partial void OncreatetimeChanging(System.DateTime value);
    partial void OncreatetimeChanged();
    partial void OndeletedChanging(byte value);
    partial void OndeletedChanged();
    #endregion
		
		public tbl_apppatch()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uid", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long uid
		{
			get
			{
				return this._uid;
			}
			set
			{
				if ((this._uid != value))
				{
					this.OnuidChanging(value);
					this.SendPropertyChanging();
					this._uid = value;
					this.SendPropertyChanged("uid");
					this.OnuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_versionCode", DbType="Int NOT NULL")]
		public int versionCode
		{
			get
			{
				return this._versionCode;
			}
			set
			{
				if ((this._versionCode != value))
				{
					this.OnversionCodeChanging(value);
					this.SendPropertyChanging();
					this._versionCode = value;
					this.SendPropertyChanged("versionCode");
					this.OnversionCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_versionName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string versionName
		{
			get
			{
				return this._versionName;
			}
			set
			{
				if ((this._versionName != value))
				{
					this.OnversionNameChanging(value);
					this.SendPropertyChanging();
					this._versionName = value;
					this.SendPropertyChanged("versionName");
					this.OnversionNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_patchpath", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string patchpath
		{
			get
			{
				return this._patchpath;
			}
			set
			{
				if ((this._patchpath != value))
				{
					this.OnpatchpathChanging(value);
					this.SendPropertyChanging();
					this._patchpath = value;
					this.SendPropertyChanged("patchpath");
					this.OnpatchpathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createtime", DbType="DateTime NOT NULL")]
		public System.DateTime createtime
		{
			get
			{
				return this._createtime;
			}
			set
			{
				if ((this._createtime != value))
				{
					this.OncreatetimeChanging(value);
					this.SendPropertyChanging();
					this._createtime = value;
					this.SendPropertyChanged("createtime");
					this.OncreatetimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleted", DbType="TinyInt NOT NULL")]
		public byte deleted
		{
			get
			{
				return this._deleted;
			}
			set
			{
				if ((this._deleted != value))
				{
					this.OndeletedChanging(value);
					this.SendPropertyChanging();
					this._deleted = value;
					this.SendPropertyChanged("deleted");
					this.OndeletedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_authlog")]
	public partial class tbl_authlog : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _uid;
		
		private string _logintoken;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuidChanging(long value);
    partial void OnuidChanged();
    partial void OnlogintokenChanging(string value);
    partial void OnlogintokenChanged();
    #endregion
		
		public tbl_authlog()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uid", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long uid
		{
			get
			{
				return this._uid;
			}
			set
			{
				if ((this._uid != value))
				{
					this.OnuidChanging(value);
					this.SendPropertyChanging();
					this._uid = value;
					this.SendPropertyChanged("uid");
					this.OnuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logintoken", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string logintoken
		{
			get
			{
				return this._logintoken;
			}
			set
			{
				if ((this._logintoken != value))
				{
					this.OnlogintokenChanging(value);
					this.SendPropertyChanging();
					this._logintoken = value;
					this.SendPropertyChanged("logintoken");
					this.OnlogintokenChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_driverdownlog")]
	public partial class tbl_driverdownlog : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _uid;
		
		private long _userid;
		
		private long _driverid;
		
		private System.Nullable<System.DateTime> _starttime;
		
		private System.Nullable<System.DateTime> _endtime;
		
		private byte _result;
		
		private byte _deleted;
		
		private EntityRef<tbl_user> _tbl_user;
		
		private EntityRef<tbl_driverinfo> _tbl_driverinfo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuidChanging(long value);
    partial void OnuidChanged();
    partial void OnuseridChanging(long value);
    partial void OnuseridChanged();
    partial void OndriveridChanging(long value);
    partial void OndriveridChanged();
    partial void OnstarttimeChanging(System.Nullable<System.DateTime> value);
    partial void OnstarttimeChanged();
    partial void OnendtimeChanging(System.Nullable<System.DateTime> value);
    partial void OnendtimeChanged();
    partial void OnresultChanging(byte value);
    partial void OnresultChanged();
    partial void OndeletedChanging(byte value);
    partial void OndeletedChanged();
    #endregion
		
		public tbl_driverdownlog()
		{
			this._tbl_user = default(EntityRef<tbl_user>);
			this._tbl_driverinfo = default(EntityRef<tbl_driverinfo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uid", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long uid
		{
			get
			{
				return this._uid;
			}
			set
			{
				if ((this._uid != value))
				{
					this.OnuidChanging(value);
					this.SendPropertyChanging();
					this._uid = value;
					this.SendPropertyChanged("uid");
					this.OnuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="BigInt NOT NULL")]
		public long userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					if (this._tbl_user.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnuseridChanging(value);
					this.SendPropertyChanging();
					this._userid = value;
					this.SendPropertyChanged("userid");
					this.OnuseridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_driverid", DbType="BigInt NOT NULL")]
		public long driverid
		{
			get
			{
				return this._driverid;
			}
			set
			{
				if ((this._driverid != value))
				{
					if (this._tbl_driverinfo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OndriveridChanging(value);
					this.SendPropertyChanging();
					this._driverid = value;
					this.SendPropertyChanged("driverid");
					this.OndriveridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_starttime", DbType="DateTime")]
		public System.Nullable<System.DateTime> starttime
		{
			get
			{
				return this._starttime;
			}
			set
			{
				if ((this._starttime != value))
				{
					this.OnstarttimeChanging(value);
					this.SendPropertyChanging();
					this._starttime = value;
					this.SendPropertyChanged("starttime");
					this.OnstarttimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endtime", DbType="DateTime")]
		public System.Nullable<System.DateTime> endtime
		{
			get
			{
				return this._endtime;
			}
			set
			{
				if ((this._endtime != value))
				{
					this.OnendtimeChanging(value);
					this.SendPropertyChanging();
					this._endtime = value;
					this.SendPropertyChanged("endtime");
					this.OnendtimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_result", DbType="TinyInt NOT NULL")]
		public byte result
		{
			get
			{
				return this._result;
			}
			set
			{
				if ((this._result != value))
				{
					this.OnresultChanging(value);
					this.SendPropertyChanging();
					this._result = value;
					this.SendPropertyChanged("result");
					this.OnresultChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleted", DbType="TinyInt NOT NULL")]
		public byte deleted
		{
			get
			{
				return this._deleted;
			}
			set
			{
				if ((this._deleted != value))
				{
					this.OndeletedChanging(value);
					this.SendPropertyChanging();
					this._deleted = value;
					this.SendPropertyChanged("deleted");
					this.OndeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_user_tbl_driverdownlog", Storage="_tbl_user", ThisKey="userid", OtherKey="uid", IsForeignKey=true)]
		public tbl_user tbl_user
		{
			get
			{
				return this._tbl_user.Entity;
			}
			set
			{
				tbl_user previousValue = this._tbl_user.Entity;
				if (((previousValue != value) 
							|| (this._tbl_user.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_user.Entity = null;
						previousValue.tbl_driverdownlogs.Remove(this);
					}
					this._tbl_user.Entity = value;
					if ((value != null))
					{
						value.tbl_driverdownlogs.Add(this);
						this._userid = value.uid;
					}
					else
					{
						this._userid = default(long);
					}
					this.SendPropertyChanged("tbl_user");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_driverinfo_tbl_driverdownlog", Storage="_tbl_driverinfo", ThisKey="driverid", OtherKey="uid", IsForeignKey=true)]
		public tbl_driverinfo tbl_driverinfo
		{
			get
			{
				return this._tbl_driverinfo.Entity;
			}
			set
			{
				tbl_driverinfo previousValue = this._tbl_driverinfo.Entity;
				if (((previousValue != value) 
							|| (this._tbl_driverinfo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_driverinfo.Entity = null;
						previousValue.tbl_driverdownlogs.Remove(this);
					}
					this._tbl_driverinfo.Entity = value;
					if ((value != null))
					{
						value.tbl_driverdownlogs.Add(this);
						this._driverid = value.uid;
					}
					else
					{
						this._driverid = default(long);
					}
					this.SendPropertyChanged("tbl_driverinfo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_driverinfo")]
	public partial class tbl_driverinfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _uid;
		
		private string _name;
		
		private long _telid;
		
		private string _sysver;
		
		private string _filepath;
		
		private System.DateTime _createtime;
		
		private byte _deleted;
		
		private EntitySet<tbl_driverdownlog> _tbl_driverdownlogs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuidChanging(long value);
    partial void OnuidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OntelidChanging(long value);
    partial void OntelidChanged();
    partial void OnsysverChanging(string value);
    partial void OnsysverChanged();
    partial void OnfilepathChanging(string value);
    partial void OnfilepathChanged();
    partial void OncreatetimeChanging(System.DateTime value);
    partial void OncreatetimeChanged();
    partial void OndeletedChanging(byte value);
    partial void OndeletedChanged();
    #endregion
		
		public tbl_driverinfo()
		{
			this._tbl_driverdownlogs = new EntitySet<tbl_driverdownlog>(new Action<tbl_driverdownlog>(this.attach_tbl_driverdownlogs), new Action<tbl_driverdownlog>(this.detach_tbl_driverdownlogs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uid", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long uid
		{
			get
			{
				return this._uid;
			}
			set
			{
				if ((this._uid != value))
				{
					this.OnuidChanging(value);
					this.SendPropertyChanging();
					this._uid = value;
					this.SendPropertyChanged("uid");
					this.OnuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telid", DbType="BigInt NOT NULL")]
		public long telid
		{
			get
			{
				return this._telid;
			}
			set
			{
				if ((this._telid != value))
				{
					this.OntelidChanging(value);
					this.SendPropertyChanging();
					this._telid = value;
					this.SendPropertyChanged("telid");
					this.OntelidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sysver", DbType="NVarChar(100)")]
		public string sysver
		{
			get
			{
				return this._sysver;
			}
			set
			{
				if ((this._sysver != value))
				{
					this.OnsysverChanging(value);
					this.SendPropertyChanging();
					this._sysver = value;
					this.SendPropertyChanged("sysver");
					this.OnsysverChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_filepath", DbType="NVarChar(300)")]
		public string filepath
		{
			get
			{
				return this._filepath;
			}
			set
			{
				if ((this._filepath != value))
				{
					this.OnfilepathChanging(value);
					this.SendPropertyChanging();
					this._filepath = value;
					this.SendPropertyChanged("filepath");
					this.OnfilepathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createtime", DbType="DateTime NOT NULL")]
		public System.DateTime createtime
		{
			get
			{
				return this._createtime;
			}
			set
			{
				if ((this._createtime != value))
				{
					this.OncreatetimeChanging(value);
					this.SendPropertyChanging();
					this._createtime = value;
					this.SendPropertyChanged("createtime");
					this.OncreatetimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleted", DbType="TinyInt NOT NULL")]
		public byte deleted
		{
			get
			{
				return this._deleted;
			}
			set
			{
				if ((this._deleted != value))
				{
					this.OndeletedChanging(value);
					this.SendPropertyChanging();
					this._deleted = value;
					this.SendPropertyChanged("deleted");
					this.OndeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_driverinfo_tbl_driverdownlog", Storage="_tbl_driverdownlogs", ThisKey="uid", OtherKey="driverid")]
		public EntitySet<tbl_driverdownlog> tbl_driverdownlogs
		{
			get
			{
				return this._tbl_driverdownlogs;
			}
			set
			{
				this._tbl_driverdownlogs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_driverdownlogs(tbl_driverdownlog entity)
		{
			this.SendPropertyChanging();
			entity.tbl_driverinfo = this;
		}
		
		private void detach_tbl_driverdownlogs(tbl_driverdownlog entity)
		{
			this.SendPropertyChanging();
			entity.tbl_driverinfo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_telapps")]
	public partial class tbl_telapp : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _uid;
		
		private long _telid;
		
		private string _appname;
		
		private string _appversion;
		
		private System.DateTime _installtime;
		
		private byte _deleted;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuidChanging(long value);
    partial void OnuidChanged();
    partial void OntelidChanging(long value);
    partial void OntelidChanged();
    partial void OnappnameChanging(string value);
    partial void OnappnameChanged();
    partial void OnappversionChanging(string value);
    partial void OnappversionChanged();
    partial void OninstalltimeChanging(System.DateTime value);
    partial void OninstalltimeChanged();
    partial void OndeletedChanging(byte value);
    partial void OndeletedChanged();
    #endregion
		
		public tbl_telapp()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uid", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long uid
		{
			get
			{
				return this._uid;
			}
			set
			{
				if ((this._uid != value))
				{
					this.OnuidChanging(value);
					this.SendPropertyChanging();
					this._uid = value;
					this.SendPropertyChanged("uid");
					this.OnuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telid", DbType="BigInt NOT NULL")]
		public long telid
		{
			get
			{
				return this._telid;
			}
			set
			{
				if ((this._telid != value))
				{
					this.OntelidChanging(value);
					this.SendPropertyChanging();
					this._telid = value;
					this.SendPropertyChanged("telid");
					this.OntelidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_appname", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string appname
		{
			get
			{
				return this._appname;
			}
			set
			{
				if ((this._appname != value))
				{
					this.OnappnameChanging(value);
					this.SendPropertyChanging();
					this._appname = value;
					this.SendPropertyChanged("appname");
					this.OnappnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_appversion", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string appversion
		{
			get
			{
				return this._appversion;
			}
			set
			{
				if ((this._appversion != value))
				{
					this.OnappversionChanging(value);
					this.SendPropertyChanging();
					this._appversion = value;
					this.SendPropertyChanged("appversion");
					this.OnappversionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_installtime", DbType="DateTime NOT NULL")]
		public System.DateTime installtime
		{
			get
			{
				return this._installtime;
			}
			set
			{
				if ((this._installtime != value))
				{
					this.OninstalltimeChanging(value);
					this.SendPropertyChanging();
					this._installtime = value;
					this.SendPropertyChanged("installtime");
					this.OninstalltimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleted", DbType="TinyInt NOT NULL")]
		public byte deleted
		{
			get
			{
				return this._deleted;
			}
			set
			{
				if ((this._deleted != value))
				{
					this.OndeletedChanging(value);
					this.SendPropertyChanging();
					this._deleted = value;
					this.SendPropertyChanged("deleted");
					this.OndeletedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_telinfo")]
	public partial class tbl_telinfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _uid;
		
		private string _type;
		
		private string _vendor;
		
		private string _sysver;
		
		private string _serial;
		
		private string _imei;
		
		private byte _deleted;
		
		private EntitySet<tbl_apkinstalllog> _tbl_apkinstalllogs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuidChanging(long value);
    partial void OnuidChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    partial void OnvendorChanging(string value);
    partial void OnvendorChanged();
    partial void OnsysverChanging(string value);
    partial void OnsysverChanged();
    partial void OnserialChanging(string value);
    partial void OnserialChanged();
    partial void OnimeiChanging(string value);
    partial void OnimeiChanged();
    partial void OndeletedChanging(byte value);
    partial void OndeletedChanged();
    #endregion
		
		public tbl_telinfo()
		{
			this._tbl_apkinstalllogs = new EntitySet<tbl_apkinstalllog>(new Action<tbl_apkinstalllog>(this.attach_tbl_apkinstalllogs), new Action<tbl_apkinstalllog>(this.detach_tbl_apkinstalllogs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uid", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long uid
		{
			get
			{
				return this._uid;
			}
			set
			{
				if ((this._uid != value))
				{
					this.OnuidChanging(value);
					this.SendPropertyChanging();
					this._uid = value;
					this.SendPropertyChanged("uid");
					this.OnuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vendor", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string vendor
		{
			get
			{
				return this._vendor;
			}
			set
			{
				if ((this._vendor != value))
				{
					this.OnvendorChanging(value);
					this.SendPropertyChanging();
					this._vendor = value;
					this.SendPropertyChanged("vendor");
					this.OnvendorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sysver", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string sysver
		{
			get
			{
				return this._sysver;
			}
			set
			{
				if ((this._sysver != value))
				{
					this.OnsysverChanging(value);
					this.SendPropertyChanging();
					this._sysver = value;
					this.SendPropertyChanged("sysver");
					this.OnsysverChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_serial", DbType="NVarChar(100)")]
		public string serial
		{
			get
			{
				return this._serial;
			}
			set
			{
				if ((this._serial != value))
				{
					this.OnserialChanging(value);
					this.SendPropertyChanging();
					this._serial = value;
					this.SendPropertyChanged("serial");
					this.OnserialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imei", DbType="NVarChar(100)")]
		public string imei
		{
			get
			{
				return this._imei;
			}
			set
			{
				if ((this._imei != value))
				{
					this.OnimeiChanging(value);
					this.SendPropertyChanging();
					this._imei = value;
					this.SendPropertyChanged("imei");
					this.OnimeiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleted", DbType="TinyInt NOT NULL")]
		public byte deleted
		{
			get
			{
				return this._deleted;
			}
			set
			{
				if ((this._deleted != value))
				{
					this.OndeletedChanging(value);
					this.SendPropertyChanging();
					this._deleted = value;
					this.SendPropertyChanged("deleted");
					this.OndeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_telinfo_tbl_apkinstalllog", Storage="_tbl_apkinstalllogs", ThisKey="uid", OtherKey="telid")]
		public EntitySet<tbl_apkinstalllog> tbl_apkinstalllogs
		{
			get
			{
				return this._tbl_apkinstalllogs;
			}
			set
			{
				this._tbl_apkinstalllogs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_apkinstalllogs(tbl_apkinstalllog entity)
		{
			this.SendPropertyChanging();
			entity.tbl_telinfo = this;
		}
		
		private void detach_tbl_apkinstalllogs(tbl_apkinstalllog entity)
		{
			this.SendPropertyChanging();
			entity.tbl_telinfo = null;
		}
	}
}
#pragma warning restore 1591
